name: Release

description: Release packages

inputs:
  git_bot_token:
    description: Git bot token
    required: true
  npm_token:
    description: NPM token
    required: true

runs:
  using: composite
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Configure npm for publishing
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm_token }}" > ~/.npmrc
        echo "registry=https://registry.npmjs.org/" >> ~/.npmrc

    - name: Release
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
        GITHUB_TOKEN: ${{ inputs.git_bot_token }}
      # Use npm for publishing by creating .yarnrc.yml to specify npm as publishConfig
      shell: bash
      run: |
        cat > .yarnrc.yml << EOF
        npmPublishRegistry: "https://registry.npmjs.org/"
        npmAuthToken: "${{ inputs.npm_token }}"
        EOF
        npx --yes nx release --yes

    - name: hack remove 'swc-angular-{version}' tag until this is fixed https://github.com/nrwl/nx/issues/22798
      shell: bash
      run: git tag -d 'swc-angular-{version}' || true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.git_bot_token }}
        branch: ${{ github.ref }}
        force: true
        tags: true
