name: 'Nx migrate'

on:
  workflow_dispatch:
  schedule:
    # Every day at 6am UTC
    - cron: '0 6 * * *'

jobs:
  nx-migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          git_bot_token: ${{ secrets.GIT_BOT_TOKEN }}

      - name: Check if @nx/workspace is outdated
        id: nrwl-workspace-outdated
        run: |
          IS_OUTDATED=$(test ! -z "$(npm outdated @nx/workspace)" && echo true || echo false)
          echo $IS_OUTDATED
          echo "outdated=$IS_OUTDATED" >> $GITHUB_OUTPUT

      - name: Update @nx/workspace
        if: steps.nrwl-workspace-outdated.outputs.outdated == 'true'
        run: yarn nx migrate latest

      - name: Install dependencies
        if: steps.nrwl-workspace-outdated.outputs.outdated == 'true'
        run: yarn install --no-immutable

      - name: Check if has migrations
        id: nrwl-workspace-has-migrations
        run: |
          HAS_MIGRATIONS=$(test -f migrations.json && echo true || echo false)
          echo $HAS_MIGRATIONS
          echo "has_migrations=$HAS_MIGRATIONS" >> $GITHUB_OUTPUT

      - name: Run @nx/workspace migrations
        if: steps.nrwl-workspace-has-migrations.outputs.has_migrations == 'true'
        run: yarn nx migrate --run-migrations

      - name: Test
        id: test
        if: steps.nrwl-workspace-outdated.outputs.outdated == 'true'
        continue-on-error: true
        run: |
          yarn nx affected --base=last-release --target=build
          yarn nx affected --base=last-release --target=lint
          yarn nx affected --base=last-release --target=test
          yarn nx affected --base=last-release --target=component-test --parallel=1
          yarn nx affected --base=last-release --target=e2e --parallel=1

      - name: Commit changes
        if: steps.nrwl-workspace-outdated.outputs.outdated == 'true'
        run: |
          LAST_VERSION=$(npm view @nx/workspace version)
          git add .
          [[ $(git status --porcelain) ]] && git commit -m "build: 📦 update nrwl workspace to ${LAST_VERSION}" || echo "nothing to commit"

      - name: Remove migrations.json & commit
        if: steps.nrwl-workspace-has-migrations.outputs.has_migrations == 'true'
        run: |
          git rm -f migrations.json
          git commit -m "build: 📦 remove migrations.json"

      - name: Push changes
        if: steps.nrwl-workspace-outdated.outputs.outdated == 'true' && steps.test.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true

      - name: Create PR
        if: steps.nrwl-workspace-outdated.outputs.outdated == 'true' && steps.test.outcome != 'success'
        run: |
          LAST_VERSION=$(npm view @nx/workspace version)
          BRANCH="update-nrwl-workspace-${LAST_VERSION}"
          git checkout -b ${BRANCH}
          git push -f --set-upstream origin ${BRANCH}
          gh pr view ${BRANCH} || gh pr create -t "Update @nx/workspace to ${BRANCH}" -b "Update @nx/workspace dependencies to ${LAST_VERSION}."
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
